version: '2'

services:
    plank:
        image: php:7.1-cli
        working_dir: /var/www/html
        entrypoint: /bin/bash -c /var/www/html/opt/app/entrypoint.sh
        volumes:
            - .:/var/www/html
        ports:
          - 8899:8899
          - 7001:7001
        depends_on:
          - rethinkdb
        external_links:
          - rethinkdb:rdb

    rethinkdb:
        image: rethinkdb:2.3.5
        ports:
          - 8080:8080
